<?php

return [
    'inappropriate_words' => [
        // Common English curse words
        'haha',
        'fuck',
        'fucker',
        'shit',
        'bitch',
        'asshole',
        'bastard',
        'dumbass',
        'dipshit',
        'jackass',
        'motherfucker',
        'son of a bitch',
        'cunt',
        'dick',
        'cock',
        'pussy',
        'whore',
        'slut',
        'faggot',
        'retard',
        'douchebag',
        'prick',
        'wanker',
        'twat',
        'bollocks',
        'bugger',
        'arse',
        'bloody hell',
        'die',
        'heck',
        'hell',
        'bitch',
        'kill',

        // Common Filipino curse words
        'gago',
        'gaga',
        'tanga',
        'bobo',
        'boba',
        'gunggong',
        'ulol',
        'tarantado',
        'tarantada',
        'pakyu',
        'puke',
        'kantot',
        'iyot',
        'hindot',
        'kupal',
        'putangina',
        'tangina',
        'puta',
        'leche',
        'lecheng',
        'lintik',
        'hayop',
        'punyeta',
        'siraulo',
        'tite',
        'titi',
        'pekpek',
        'kiki',

        // Derogatory terms
        'unggoy',
        'baboy',
        'bakla' // Context-dependent, can be offensive in certain cases
    ],
];
